# Generated by Django 5.2.4 on 2025-07-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("day", models.DateField()),
                ("priority", models.CharField(max_length=20)),
                ("tags", models.CharField(max_length=50)),
                ("esttime", models.DurationField()),
            ],
        ),
    ]
