# Generated by Django 5.2.4 on 2025-07-26 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_todo_tags_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.category'),
        ),
    ]
